### **Task 1 -**

In [1]:
import pandas as pd

In [2]:
ds = pd.read_csv("Toyota.csv")

In [3]:
print(ds)

      Price   Age     KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  23.0  46986   Diesel   90       1.0          0  2000  three
1     13750  23.0  72937   Diesel   90       1.0          0  2000      3
2     13950  24.0  41711   Diesel   90       NaN          0  2000      3
3     14950  26.0  48000   Diesel   90       0.0          0  2000      3
4     13750  30.0  38500   Diesel   90       0.0          0  2000      3
...     ...   ...    ...      ...  ...       ...        ...   ...    ...
1431   7500   NaN  20544   Petrol   86       1.0          0  1300      3
1432  10845  72.0     ??   Petrol   86       0.0          0  1300      3
1433   8500   NaN  17016   Petrol   86       0.0          0  1300      3
1434   7250  70.0     ??      NaN   86       1.0          0  1300      3
1435   6950  76.0      1   Petrol  110       0.0          0  1600      5

      Weight
0       1165
1       1165
2       1165
3       1165
4       1170
...      ...
1431    1025
1432    1015
1433    1015
1434    1015
1435    1114

[1436 rows x 10 columns]

In [4]:
ds.head()

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170

In [5]:
ds.tail()

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [6]:
# ds.Price
ds['Price']

0       13500
1       13750
2       13950
3       14950
4       13750
        ...
1431     7500
1432    10845
1433     8500
1434     7250
1435     6950
Name: Price, Length: 1436, dtype: int64

In [8]:
ds.Price.head()

0    13500
1    13750
2    13950
3    14950
4    13750
Name: Price, dtype: int64

In [11]:
ds['Price'].head(25)

0     13500
1     13750
2     13950
3     14950
4     13750
5     12950
6     16900
7     18600
8     21500
9     12950
10    20950
11    19950
12    19600
13    21500
14    22500
15    22000
16    22750
17    17950
18    16750
19    16950
20    15950
21    16950
22    15950
23    16950
24    16250
Name: Price, dtype: int64

In [12]:
ds.shape

(1436, 10)

In [13]:
ds.size

14360

In [14]:
ds.dtypes

Price          int64
Age          float64
KM            object
FuelType      object
HP            object
MetColor     float64
Automatic      int64
CC             int64
Doors         object
Weight         int64
dtype: object

In [17]:
ds.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [20]:
# ds.at[3, 'FuelType']
ds.loc[3, 'FuelType']

'Diesel'

In [24]:
ds.iat[3,3]

'Diesel'

In [23]:
# ds.iat[3, 1]
ds.iloc[3, 1]

26.0

In [29]:
# ds['FuelType'] or
ds.loc[:, "FuelType"]

# at = single value
# iat = single value at index
# loc= multiple value
# iloc multiple value at index

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434       NaN
1435    Petrol
Name: FuelType, Length: 1436, dtype: object

In [31]:
ds.loc[3:10, 'FuelType']

3     Diesel
4     Diesel
5     Diesel
6     Diesel
7        NaN
8     Petrol
9     Diesel
10    Petrol
Name: FuelType, dtype: object

In [33]:
# ds[['KM', 'HP', 'Automatic']]
ds.loc[:,["FuelType", "Age","KM"]]

     FuelType   Age     KM
0      Diesel  23.0  46986
1      Diesel  23.0  72937
2      Diesel  24.0  41711
3      Diesel  26.0  48000
4      Diesel  30.0  38500
...       ...   ...    ...
1431   Petrol   NaN  20544
1432   Petrol  72.0     ??
1433   Petrol   NaN  17016
1434      NaN  70.0     ??
1435   Petrol  76.0      1

[1436 rows x 3 columns]

In [38]:
ds.iloc[0:5, 1:4]
# second number is exclusive

    Age     KM FuelType
0  23.0  46986   Diesel
1  23.0  72937   Diesel
2  24.0  41711   Diesel
3  26.0  48000   Diesel
4  30.0  38500   Diesel

In [39]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1436 non-null   object
 3   FuelType   1336 non-null   object
 4   HP         1436 non-null   object
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 112.3+ KB

In [40]:
# Observations -
# dataset has 10 columns and 1436 rows
# 4 columns have object dtype, 4 have int64 and 2 have float64
# columns like 'Age', 'FuelType', 'MetColor' have missing/null values

In [43]:
ds['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [44]:
ds['HP'].unique()

array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [45]:
ds['Automatic'].unique()

array([0, 1])

In [48]:
ds['KM'].head(100).unique()

array(['46986', '72937', '41711', '48000', '38500', '61000', '??',
       '75889', '19700', '71138', '31461', '43610', '32189', '23000',
       '34131', '18739', '34000', '21716', '25563', '64359', '67660',
       '43905', '56349', '32220', '25813', '28450', '34545', '41415',
       '44142', '11090', '9750', '35199', '29510', '32692', '41000',
       '43000', '25000', '10000', '25329', '27500', '49059', '44068',
       '46961', '110404', '100250', '84000', '79375', '75048', '72215',
       '64982', '62636', '57086', '56000', '49866', '49163', '45725',
       '43210', '39704', '38950', '37400', '37177', '36544', '33511',
       '32181', '30993', '30400', '30000', '29719', '29206', '29198',
       '28817', '28227', '28000', '25266', '23489', '22575', '22000',
       '20019', '20000', '17003', '16238', '15414', '8537', '7000',
       '66966', '51884', '50005', '48110', '34472', '33329', '31850',
       '30351', '29435', '25948', '24500', '23902'], dtype=object)

In [49]:
ds2 = pd.read_csv('Toyota.csv', na_values=["??", "????"])

In [50]:
print(ds2)

      Price   Age       KM FuelType     HP  MetColor  Automatic    CC  Doors  \
0     13500  23.0  46986.0   Diesel   90.0       1.0          0  2000  three
1     13750  23.0  72937.0   Diesel   90.0       1.0          0  2000      3
2     13950  24.0  41711.0   Diesel   90.0       NaN          0  2000      3
3     14950  26.0  48000.0   Diesel   90.0       0.0          0  2000      3
4     13750  30.0  38500.0   Diesel   90.0       0.0          0  2000      3
...     ...   ...      ...      ...    ...       ...        ...   ...    ...
1431   7500   NaN  20544.0   Petrol   86.0       1.0          0  1300      3
1432  10845  72.0      NaN   Petrol   86.0       0.0          0  1300      3
1433   8500   NaN  17016.0   Petrol   86.0       0.0          0  1300      3
1434   7250  70.0      NaN      NaN   86.0       1.0          0  1300      3
1435   6950  76.0      1.0   Petrol  110.0       0.0          0  1600      5

      Weight
0       1165
1       1165
2       1165
3       1165
4       1170
...      ...
1431    1025
1432    1015
1433    1015
1434    1015
1435    1114

[1436 rows x 10 columns]

In [51]:
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 112.3+ KB

In [52]:
ds2["KM"].head(100).unique()

array([ 46986.,  72937.,  41711.,  48000.,  38500.,  61000.,     nan,
        75889.,  19700.,  71138.,  31461.,  43610.,  32189.,  23000.,
        34131.,  18739.,  34000.,  21716.,  25563.,  64359.,  67660.,
        43905.,  56349.,  32220.,  25813.,  28450.,  34545.,  41415.,
        44142.,  11090.,   9750.,  35199.,  29510.,  32692.,  41000.,
        43000.,  25000.,  10000.,  25329.,  27500.,  49059.,  44068.,
        46961., 110404., 100250.,  84000.,  79375.,  75048.,  72215.,
        64982.,  62636.,  57086.,  56000.,  49866.,  49163.,  45725.,
        43210.,  39704.,  38950.,  37400.,  37177.,  36544.,  33511.,
        32181.,  30993.,  30400.,  30000.,  29719.,  29206.,  29198.,
        28817.,  28227.,  28000.,  25266.,  23489.,  22575.,  22000.,
        20019.,  20000.,  17003.,  16238.,  15414.,   8537.,   7000.,
        66966.,  51884.,  50005.,  48110.,  34472.,  33329.,  31850.,
        30351.,  29435.,  25948.,  24500.,  23902.])

In [53]:
ds2['Doors'].replace('three', 3, inplace=True)
ds2['Doors'].replace('four', 4, inplace=True)
ds2['Doors'].replace('five', 5, inplace=True)

In [54]:
ds2["Doors"].unique()

array([3, '3', '5', '4', 4, 5, '2'], dtype=object)

In [66]:
ds2['Doors'] = ds2['Doors'].astype('int')
ds2['MetColor'] = ds2['MetColor'].astype('object')
ds2['Automatic'] = ds2['Automatic'].astype('int')

In [67]:
ds2["Doors"].info()

<class 'pandas.core.series.Series'>
Int64Index: 1096 entries, 0 to 1435
Series name: Doors
Non-Null Count  Dtype
--------------  -----
1096 non-null   int64
dtypes: int64(1)
memory usage: 17.1 KB

In [57]:
ds2.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [58]:
ds2 = ds2.dropna()

In [59]:
ds2.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64

In [60]:
ds2.shape

(1096, 10)

In [61]:
ds2['FuelType'].unique()

array(['Diesel', 'Petrol', 'CNG'], dtype=object)

In [62]:
ds2.FuelType.value_counts()

Petrol    968
Diesel    116
CNG        12
Name: FuelType, dtype: int64

In [69]:
ds2[ds2['FuelType']=='Diesel']

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,3,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170
5,12950,32.0,61000.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1109,8950,76.0,120263.0,Diesel,72.0,1.0,0,2000,5,1135
1118,8950,73.0,112963.0,Diesel,72.0,1.0,0,2000,5,1135
1195,8750,74.0,89800.0,Diesel,72.0,1.0,0,2000,3,1115
1202,6950,73.0,88186.0,Diesel,72.0,1.0,0,2000,3,1115
1216,8500,70.0,85864.0,Diesel,72.0,1.0,0,2000,5,1135

In [70]:
ds2[ds2['FuelType']=='Diesel'].KM.mean()

118046.54310344828

In [71]:
ds2[ds2['KM']=='??']

Empty DataFrame
Columns: [Price, Age, KM, FuelType, HP, MetColor, Automatic, CC, Doors, Weight]
Index: []

### **Task 2 -**

In [73]:
df = pd.read_csv("adult.csv")

In [74]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [75]:
df["relationship"].unique()
# df.relationship.unique()

array(['Own-child', 'Husband', 'Not-in-family', 'Unmarried', 'Wife',
       'Other-relative'], dtype=object)

In [76]:
from sklearn import preprocessing

In [77]:
label_encoder = preprocessing.LabelEncoder()

In [78]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [79]:
df["relationship_coded"] = label_encoder.fit_transform(df["relationship"])

In [81]:
df["relationship_coded"]

0        3
1        0
2        0
3        0
4        3
        ..
48837    5
48838    0
48839    4
48840    3
48841    5
Name: relationship_coded, Length: 48842, dtype: int64

In [84]:
df.relationship.value_counts()

Husband           19716
Not-in-family     12583
Own-child          7581
Unmarried          5125
Wife               2331
Other-relative     1506
Name: relationship, dtype: int64

In [82]:
# one hot encoding
df_new = pd.get_dummies(df, columns=["relationship"])

In [83]:
df_new

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,race,gender,capital-gain,...,hours-per-week,native-country,income,relationship_coded,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Black,Male,0,...,40,United-States,<=50K,3,0,0,0,1,0,0
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,White,Male,0,...,50,United-States,<=50K,0,1,0,0,0,0,0
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,White,Male,0,...,40,United-States,>50K,0,1,0,0,0,0,0
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Black,Male,7688,...,40,United-States,>50K,0,1,0,0,0,0,0
4,18,?,103497,Some-college,10,Never-married,?,White,Female,0,...,30,United-States,<=50K,3,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,White,Female,0,...,38,United-States,<=50K,5,0,0,0,0,0,1
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,White,Male,0,...,40,United-States,>50K,0,1,0,0,0,0,0
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,White,Female,0,...,40,United-States,<=50K,4,0,0,0,0,1,0
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,White,Male,0,...,20,United-States,<=50K,3,0,0,0,1,0,0
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,White,Female,15024,...,40,United-States,>50K,5,0,0,0,0,0,1